config/routes.rb
Rails.application.routes.draw do
  resources :tracks

  resources :engines

  resources :cars

  resources :prototypes

  resources :railroads

  resources :manufacturers

  devise_for :users

  resources :users, :only => [:show]

  get 'home/about'
  get 'home/index'
  root 'home#index'

end

app/models/engine.rb
class Engine < ActiveRecord::Base
	def self.owner(user)
	    where("user_id = ?", user.id)
	end

	belongs_to :User
	belongs_to :Manufacturer
	belongs_to :Prototype
	belongs_to :Railroad
end

app/controllers/engines_controller.rb
class EnginesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_engine, only: [:show, :edit, :update, :destroy]
  before_action :build_picklists, only: [:new , :edit]

  # GET /engines
  # GET /engines.json
  def index
    @engines = Engine.owner(current_user)
  end

  # GET /engines/1
  # GET /engines/1.json
  def show
  end

  # GET /engines/new
  def new
    @engine = Engine.new
  end

  # GET /engines/1/edit
  def edit
  end

  # POST /engines
  # POST /engines.json
  def create
    @engine = Engine.new(engine_params)

    respond_to do |format|
      @engine.User_id = current_user.id
      if @engine.save
        format.html { redirect_to @engine, notice: 'Engine was successfully created.' }
        format.json { render :show, status: :created, location: @engine }
      else
        format.html { render :new }
        format.json { render json: @engine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /engines/1
  # PATCH/PUT /engines/1.json
  def update
    respond_to do |format|
      if @engine.update(engine_params)
        format.html { redirect_to @engine, notice: 'Engine was successfully updated.' }
        format.json { render :show, status: :ok, location: @engine }
      else
        format.html { render :edit }
        format.json { render json: @engine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /engines/1
  # DELETE /engines/1.json
  def destroy
    @engine.destroy
    respond_to do |format|
      format.html { redirect_to engines_url, notice: 'Engine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_engine
      @engine = Engine.owner(current_user).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def engine_params
      params.require(:engine).permit(:modelnumber, :notes, :scale, :enginetype, :roadnumber, :own, :User_id, :Manufacturer_id, :Prototype_id, :Railroad_id)
    end

    def build_picklists
      @manufacturer_array = Manufacturer.owner(current_user)
      @prototype_array = Prototype.owner(current_user)
      @railroad_array = Railroad.owner(current_user)
    end
end

app/helpers/engines_helper.rb
module EnginesHelper
end

app/views/engines/_form.html.erb
<%= form_for(@engine) do |f| %>
  <% if @engine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@engine.errors.count, "error") %> prohibited this engine from being saved:</h2>

      <ul>
      <% @engine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :modelnumber %><br>
    <%= f.text_field :modelnumber %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_field :notes %>
  </div>
  <div class="field">
    <%= f.label :scale %><br>
    <%= f.select( :scale , SCALES ) %>
  </div>
  <div class="field">
    <%= f.label :enginetype %><br>
    <%= f.select( :enginetype, ENGINETYPES ) %>
  </div>
  <div class="field">
    <%= f.label :roadnumber %><br>
    <%= f.text_field :roadnumber %>
  </div>
  <div class="field">
    <%= f.label :own %><br>
    <%= f.check_box :own %>
  </div>
  <div class="field">
    <%= f.label :Manufacturer_id %><br>
    <%= f.collection_select :Manufacturer_id , @manufacturer_array, :id , :name %>
  </div>
  <div class="field">
    <%= f.label :Prototype_id %><br>
    <%= f.collection_select :Prototype_id , @prototype_array, :id , :name %>
  </div>
  <div class="field">
    <%= f.label :Railroad_id %><br>
    <%= f.collection_select :Railroad_id , @railroad_array, :id , :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/engines/edit.html.erb
<h1>Editing engine</h1>

<%= render 'form' %>

<%= link_to 'Show', @engine %> |
<%= link_to 'Back', engines_path %>

app/views/engines/index.html.erb
<h1>Listing engines</h1>

<div class="table-responsive">
<table class="table table-bordered table-condensed table-hover">
  <thead>
    <tr>
      <th><%= Engine.human_attribute_name("modelnumber") %></th>
      <th><%= Engine.human_attribute_name("scale") %></th>
      <th><%= Engine.human_attribute_name("enginetype") %></th>
      <th><%= Engine.human_attribute_name("roadnumber") %></th>
      <th><%= Engine.human_attribute_name("own") %></th>
      <th><%= Engine.human_attribute_name("Manufacturer") %></th>
      <th><%= Engine.human_attribute_name("Prototype") %></th>
      <th><%= Engine.human_attribute_name("Railroad") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @engines.each do |engine| %>
      <tr>
        <td><%= engine.modelnumber %></td>
        <td><%= engine.scale %></td>
        <td><%= engine.enginetype %></td>
        <td><%= engine.roadnumber %></td>
        <td><%= check_box "engine", "own", {:checked => engine.own, :disabled => true}%></td>
        <td><%= engine.Manufacturer.name %></td>
        <td><%= engine.Prototype.name %></td>
        <td><%= engine.Railroad.name %></td>
        <td><%= link_to 'Show', engine %></td>
        <td><%= link_to 'Edit', edit_engine_path(engine) %></td>
        <td><%= link_to 'Destroy', engine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Engine', new_engine_path %>

app/views/engines/new.html.erb
<h1>New engine</h1>

<%= render 'form' %>

<%= link_to 'Back', engines_path %>

app/views/engines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= Engine.human_attribute_name("modelnumber") %>:<strong/>
  <%= @engine.modelnumber %>
</p>

<p>
  <strong><%= Engine.human_attribute_name("notes") %>:</strong>
  <%= @engine.notes %>
</p>

<p>
  <strong><%= Engine.human_attribute_name("scale") %>:</strong>
  <%= @engine.scale %>
</p>

<p>
  <strong><%= Engine.human_attribute_name("enginetype") %>:</strong>
  <%= @engine.enginetype %>
</p>

<p>
  <strong><%= Engine.human_attribute_name("roadnumber") %>:</strong>
  <%= @engine.roadnumber %>
</p>

<p>
  <strong><%= Engine.human_attribute_name("own") %>:</strong>
  <% if @engine.own then%>
    <span class="glyphicon glyphicon-ok"></span>
  <% end %>
</p>

<p>
  <strong><%= Engine.human_attribute_name("Manufacturer") %>:</strong>
  <%= @engine.Manufacturer.name %>
</p>

<p>
  <strong><%= Engine.human_attribute_name("Prototype") %>:</strong>
  <%= @engine.Prototype.name %>
</p>

<p>
  <strong><%= Engine.human_attribute_name("Railroad") %>:</strong>
  <%= @engine.Railroad.name %>
</p>

<%= link_to 'Edit', edit_engine_path(@engine) %> |
<%= link_to 'Back', engines_path %>