config/routes.rb
Rails.application.routes.draw do
  resources :tracks

  resources :engines

  resources :cars

  resources :prototypes

  resources :railroads

  resources :manufacturers

  devise_for :users

  resources :users, :only => [:show]

  get 'home/about'
  get 'home/index'
  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :trackable, :validatable

	def self.owner(user)
	    where("id = ?", user.id)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

	#GET /users/1
	def show
		if(params[:id] != :null)
			@user = User.owner(current_user).find(params[:id])
		else
			redirect_to @home
		end
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<h2><%= @user.email %></h2>
<%= link_to 'Edit Profile', edit_user_registration_path, :class => 'btn btn-default' %>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<strong>Settings</strong>
<ul>
	<li><%= link_to "Manufacturers", manufacturers_path %></li>
	<li><%= link_to "Prototypes", prototypes_path %></li>
	<li><%= link_to "Railroads", railroads_path %></li>
</ul>

<%= link_to 'Edit Profile', edit_user_registration_path, :class => 'btn btn-default' %>
<br/>
<%= link_to "Back", :back %>