config/routes.rb
Rails.application.routes.draw do
  resources :tracks

  resources :engines

  resources :cars

  resources :prototypes

  resources :railroads

  resources :manufacturers

  devise_for :users

  resources :users, :only => [:show]

  get 'home/about'
  get 'home/index'
  root 'home#index'

end

app/models/railroad.rb
class Railroad < ActiveRecord::Base
	def self.owner(user)
	    where("user_id = ?", user.id)
	end

	belongs_to :User
end

app/controllers/railroads_controller.rb
class RailroadsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_railroad, only: [:show, :edit, :update, :destroy]

  # GET /railroads
  # GET /railroads.json
  def index
    @railroads = Railroad.owner(current_user)
  end

  # GET /railroads/1
  # GET /railroads/1.json
  def show
  end

  # GET /railroads/new
  def new
    @railroad = Railroad.new
  end

  # GET /railroads/1/edit
  def edit
  end

  # POST /railroads
  # POST /railroads.json
  def create
    @railroad = Railroad.new(railroad_params)

    respond_to do |format|
      @railroad.User_id = current_user.id
      if @railroad.save
        format.html { redirect_to @railroad, notice: 'Railroad was successfully created.' }
        format.json { render :show, status: :created, location: @railroad }
      else
        format.html { render :new }
        format.json { render json: @railroad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /railroads/1
  # PATCH/PUT /railroads/1.json
  def update
    respond_to do |format|
      if @railroad.update(railroad_params)
        format.html { redirect_to @railroad, notice: 'Railroad was successfully updated.' }
        format.json { render :show, status: :ok, location: @railroad }
      else
        format.html { render :edit }
        format.json { render json: @railroad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /railroads/1
  # DELETE /railroads/1.json
  def destroy
    @railroad.destroy
    respond_to do |format|
      format.html { redirect_to railroads_url, notice: 'Railroad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_railroad
      @railroad = Railroad.owner(current_user).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def railroad_params
      params.require(:railroad).permit(:name, :notes, :User_id)
    end
end

app/helpers/railroads_helper.rb
module RailroadsHelper
end

app/views/railroads/_form.html.erb
<%= form_for(@railroad) do |f| %>
  <% if @railroad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@railroad.errors.count, "error") %> prohibited this railroad from being saved:</h2>

      <ul>
      <% @railroad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_field :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/railroads/edit.html.erb
<h1>Editing railroad</h1>

<%= render 'form' %>

<%= link_to 'Show', @railroad %> |
<%= link_to 'Back', railroads_path %>

app/views/railroads/index.html.erb
<h1>Listing railroads</h1>

<div class="table-responsive">
<table class="table table-bordered table-condensed table-hover">
  <thead>
    <tr>
      <th><%= Railroad.human_attribute_name("name") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @railroads.each do |railroad| %>
      <tr>
        <td><%= railroad.name %></td>
        <td><%= link_to 'Show', railroad %></td>
        <td><%= link_to 'Edit', edit_railroad_path(railroad) %></td>
        <td><%= link_to 'Destroy', railroad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Railroad', new_railroad_path %>

app/views/railroads/new.html.erb
<h1>New railroad</h1>

<%= render 'form' %>

<%= link_to 'Back', railroads_path %>

app/views/railroads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= Railroad.human_attribute_name("name") %>:</strong>
  <%= @railroad.name %>
</p>

<p>
  <strong><%= Railroad.human_attribute_name("notes") %>:</strong>
  <%= @railroad.notes %>
</p>


<%= link_to 'Edit', edit_railroad_path(@railroad) %> |
<%= link_to 'Back', railroads_path %>