config/routes.rb
Rails.application.routes.draw do
  resources :tracks

  resources :engines

  resources :cars

  resources :prototypes

  resources :railroads

  resources :manufacturers

  devise_for :users

  resources :users, :only => [:show]

  get 'home/about'
  get 'home/index'
  root 'home#index'

end

app/models/car.rb
class Car < ActiveRecord::Base
	def self.owner(user)
	    where("user_id = ?", user.id)
	end

	belongs_to :User
	belongs_to :Manufacturer
	belongs_to :Railroad
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  before_action :build_picklists, only: [:new , :edit]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.owner(current_user)
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      @car.User_id = current_user.id
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.owner(current_user).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:name, :modelnumber, :notes, :scale, :cartype, :quantity, :User_id, :Manufacturer_id, :Railroad_id)
    end

    def build_picklists
      @manufacturer_array = Manufacturer.owner(current_user)
      @railroad_array = Railroad.owner(current_user)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :modelnumber %><br>
    <%= f.text_field :modelnumber %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_field :notes %>
  </div>
  <div class="field">
    <%= f.label :scale %><br>
    <%= f.select( :scale , SCALES ) %>
  </div>
  <div class="field">
    <%= f.label :cartype %><br>
    <%= f.select( :cartype , CARTYPES ) %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :Manufacturer_id %><br>
    <%= f.collection_select :Manufacturer_id , @manufacturer_array, :id , :name %>
  </div>
  <div class="field">
    <%= f.label :Railroad_id %><br>
    <%= f.collection_select :Railroad_id , @railroad_array, :id , :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<h1>Listing cars</h1>

<div class="table-responsive">
<table class="table table-bordered table-condensed table-hover">
  <thead>
    <tr>
      <th><%= Car.human_attribute_name("name") %></th>
      <th><%= Car.human_attribute_name("modelnumber") %></th>
      <th><%= Car.human_attribute_name("scale") %></th>
      <th><%= Car.human_attribute_name("cartype") %></th>
      <th><%= Car.human_attribute_name("quantity") %></th>
      <th><%= Car.human_attribute_name("Manufacturer") %></th>
      <th><%= Car.human_attribute_name("Railroad") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.name %></td>
        <td><%= car.modelnumber %></td>
        <td><%= car.scale %></td>
        <td><%= car.cartype %></td>
        <td><%= car.quantity %></td>
        <td><%= car.Manufacturer.name %></td>
        <td><%= car.Railroad.name %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= Car.human_attribute_name("name") %>:</strong>
  <%= @car.name %>
</p>

<p>
  <strong><%= Car.human_attribute_name("modelnumber") %>:</strong>
  <%= @car.modelnumber %>
</p>

<p>
  <strong><%= Car.human_attribute_name("notes") %>:</strong>
  <%= @car.notes %>
</p>

<p>
  <strong><%= Car.human_attribute_name("scale") %>:</strong>
  <%= @car.scale %>
</p>

<p>
  <strong><%= Car.human_attribute_name("cartype") %>:</strong>
  <%= @car.cartype %>
</p>

<p>
  <strong><%= Car.human_attribute_name("quantity") %>:</strong>
  <%= @car.quantity %>
</p>

<p>
  <strong><%= Car.human_attribute_name("Manufacturer") %>:</strong>
  <%= @car.Manufacturer.name %>
</p>

<p>
  <strong><%= Car.human_attribute_name("Railroad") %>:</strong>
  <%= @car.Railroad.name %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>